In [ ]:
#Week9_lab1

In [25]:
import numpy as np
A = np.arange(1, 21).reshape(4, 5)
print(A)
print(A.dtype)
print(A.ndim)
print(A.shape)
print(A.size)
print(A.itemsize)

B = A.reshape(5, 4)
print(B)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
int64
2
(4, 5)
20
8
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [23]:
import numpy as up

a=np.array([[0.,0.,0.],
           [.10,.10,.10],
           [.20,.20,.20],
           [.30,.30,.30]])
b =np.array([0.,1.,2.])
c = a + b
print("a+b:")
print(c)
mask=(c>=22)
print (mask)
count=np.sum(mask)
print("Count of vaues>=22:",count)

a+b:
[[0.  1.  2. ]
 [0.1 1.1 2.1]
 [0.2 1.2 2.2]
 [0.3 1.3 2.3]]
[[False False False]
 [False False False]
 [False False False]
 [False False False]]
Count of vaues>=22: 0


In [12]:
import numpy as np
grades = np.array([[87, 96, 70],
[100, 87, 90],
[94, 77, 90],
[100, 81, 82]])
print(np.sum(grades))
print(np.min(grades))
print(np.max(grades))
print(np.mean(grades))
print(np.std(grades))
print(np.var(grades))
print(np.mean(grades, axis=0))
print(np.mean(grades, axis=1))
print(np.max(grades, axis=1))

1054
70
100
87.83333333333333
8.792357792739987
77.30555555555556
[95.25 85.25 83.  ]
[84.33333333 92.33333333 87.         87.66666667]
[ 96 100  94 100]


In [27]:
import numpy as np

arr = np.array([[2, 4, 6],
[1, 3, 5],
[7, 9, 11]])

print(np.sum(arr, axis=1))
print(np.sum(arr, axis=0))
print(np.mean(arr))


[12  9 27]
[10 16 22]
5.333333333333333


In [28]:
import numpy as np

A = np.array([[10, 20, 30],
[40, 50, 60]])

B = np.array([1, 2, 3])

print(A + B)
print(A * 2)
print(A - 5)


[[11 22 33]
 [41 52 63]]
[[ 20  40  60]
 [ 80 100 120]]
[[ 5 15 25]
 [35 45 55]]


In [29]:
import numpy as np

grades = np.array([[70, 85, 90],
[88, 76, 95],
[60, 80, 72]])

print(np.argmax(grades))
print(np.argmax(grades, axis=1))
print(np.argmin(grades, axis=0))


5
[2 2 1]
[2 1 2]


In [ ]:
#Week9_Lab part2

In [30]:
import numpy as np

A = np.array([[5, 8, 2, 7],
[1, 9, 4, 3],
[6, 0, 11, 10],
[12, 13, 14, 15]])

print(A[1])
print(A[:, 2])
print(A[1:3, 1:3])


[1 9 4 3]
[ 2  4 11 14]
[[ 9  4]
 [ 0 11]]


In [31]:
import numpy as np

scores = np.array([[70, 80, 90],
[60, 75, 85],
[88, 92, 79],
[55, 65, 72]])

scores[:, 1] = scores[:, 1] + 5
scores[0] = [100, 100, 100]
scores[:, 2] = 0

print(scores)


[[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]


In [32]:
import numpy as np

A = np.array([[1, 2],
[3, 4]])

B = np.array([[5, 6],
[7, 8]])

v = np.array([2, 4])

print(A * B)
print(A @ B)
print(A * v)


[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[ 2  8]
 [ 6 16]]


In [33]:
import numpy as np

np.random.seed(0)

A = np.random.randint(-5, 6, (4, 4))
print(A)

values, counts = np.unique(A, return_counts=True)
print(values)
print(counts)

print(np.unique(A, axis=0))

a = np.array([[1, 0, 0],
[1, 0, 0],
[2, 3, 4]])

print(np.unique(a, axis=0))


[[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]
 [ 3  3  5 -4]]
[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[1 1 1 3 1 2 1 2 2 1 1]
[[-3 -1  2  1]
 [ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [ 3  3  5 -4]]
[[1 0 0]
 [2 3 4]]


In [39]:
import numpy as np

x = np.array([2, 0, 1, 5, 4, 1, 9])

A = np.array([[3, 8, 1],
[6, 2, 9]])

idx = np.argsort(x)
print(idx)
print(x[idx])

print(np.unravel_index(A.argmin(), A.shape))

print(np.where(x > 3))

parts = np.split(x, [2, 5])
print(parts)

x2 = np.expand_dims(x, axis=0)
print(x2)

x3 = np.squeeze(x2)
print(x3)
# expanddims يضيف بعد جديد للمصفوفة يعني يحولها من شكل 7 الى 1 7 كأنها صارت داخل صف واحد
#np squeeze يرجعها لشكلها الطبيعي ويحذف اي بعد زائد حجمه 1
#`np.expand_dims` adds a new dimension to an array. For example, it changes a shape from (7,) to (1, 7), as if the data is placed inside one row.

#np.squeeze` removes any extra dimensions of size 1 and returns the array to its original shape.


[1 2 5 0 4 3 6]
[0 1 1 2 4 5 9]
(np.int64(0), np.int64(2))
(array([3, 4, 6]),)
[array([2, 0]), array([1, 5, 4]), array([1, 9])]
[[2 0 1 5 4 1 9]]
[2 0 1 5 4 1 9]
